
export const GET_WEATHER_DATA_SUCCESS = 'GET_WEATHER_DATA_SUCCESS'
export const GET_WEATHER_DATA_LOAD = 'GET_WEATHER_DATA_LOAD'
export const GET_WEATHER_DATA_ERR = 'GET_WEATHER_DATA_ERR'

export const SET_TEMP_UNIT = 'SET_TEMP_UNIT'
export const SET_PAGE_SIZE = 'SET_PAGE_SIZE'
export const SET_SELECTED_INDEX = 'SET_SELECTED_INDEX'